input:
  image_dir: "A/img"          # 输入图像目录，包含需要进行数据增强的原始图像
  label_dir: "A/label"        # 输入标签目录，对应于输入图像的标签文件
  
output:
  image_dir: "output/images"  # 增强后图像的输出目录
  label_dir: "output/labels"  # 增强后标签文件的输出目录
  
augmentation:
  num_images: 30               # 每张图像生成5个增强版本，适用于数据量较少的情况；如果数据量大，可以适当减少
  num_operations: [3, 5]      # 每次增强时随机应用3到5个操作，增加增强的多样性，同时避免过度增强

  operations:
    flip:
      probability: 0        # 水平翻转的概率为50%，适用于方向不敏感的目标检测任务
    rotate:
      angle: [-360, 360]        # 随机旋转角度范围为-10到10度，模拟不同角度的拍摄情况
    multiply:
      range: [0.8, 1.2]       # 亮度增强的范围，将亮度调整到0.8倍到1.2倍，用于模拟不同光照条件
    scale:
      range: [0.8, 1.2]       # 缩放范围，将图像缩小到0.8倍或放大到1.2倍，适用于目标尺度的变化
    contrast:
      range: [0.75, 1.5]      # 对比度调整范围，用于模拟不同清晰度的场景，提高模型对比度变化的适应性
    hue:
      range: [-2, 2]        # 色调调整范围-10到10，用于模拟不同色彩环境下的场景
    noise:
      scale: [0, 0.05]        # 高斯噪声范围，用于增强抗噪声能力，模拟轻微的图像干扰
    perspective:
      scale: [0.01, 0.05]     # 透视变换的范围，增加轻微的视角变化，模拟不同拍摄角度
    blur:
      kernel: [3, 5]          # 模糊核大小范围为3到5，用于模拟不同清晰度的图像，提升模型的鲁棒性
  
processing:
  num_workers: 2              # 设置多线程数量，用于加速处理。
                              # 建议范围：1到CPU核心数量的2倍之间。
                              # 如果有多核CPU，设置为核心数的一半到核心数的两倍（如4核可设置为2到8），以平衡速度和资源。
                              # 注意：过高的num_workers可能导致内存占用过大，导致系统不稳定。
